- name: install {{ item }}
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - obnam
    - gnupg
- name: generate ssh key for transfer
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_file: .ssh/backup_key
  register: backup_key
- name: deploy ssh key to storage
  authorized_key:
    user: "backup-{{ backup_client_name }}"
    key: "{{ backup_key.ssh_public_key }}"
    exclusive: yes
    path: /etc/ssh/authorized_keys/backup-{{ backup_client_name }}
    manage_dir: no
  delegate_to: "{{ item }}"
  with_items:
    - "{{ backup_targets }}"
- name: generate /etc/obnam.conf
  ini_file:
    dest: /etc/obnam.conf
    section: config
    option: "{{ item['option'] }}"
    value: "{{ item['value'] }}"
  with_items:
    - option: "client-name"
      value: "{{ backup_client_name }}"
    - option: exclude-caches
      value: yes
    - option: one-file-system
      value: yes
    - option: ssh-key
      value: /root/.ssh/backup_key

# obnam --encrypt-with=BFB74804AD8ACF73894CE2AAB12DFE314A9467F3 \
# --repository=sftp://ippai@obnam/backup/ \
# backup /bin
# obnam add-key ippai --keyid <meins>
# obnam backup /

